### ISSUE TITLE
Clear action

### ISSUE THREAD

**Issue by alphaDroid89** [pedromassango/AndroidCustomView#1]
@pedromassango done a great job. 

Not sure why you missed writing action while clicking on (X) button. Please refer the below workaround if its ok please include it 😸 

```
  setOnTouchListener(View.OnTouchListener { _, event ->
            if (event.action == MotionEvent.ACTION_UP) {
                if (event.rawX >= (this.right - this.compoundPaddingRight)) {
                    this.setText("")
                    return@OnTouchListener true
                }
            }
            return@OnTouchListener false
        })
```

**Comment by pedromassango** [comment]
Good trick, I will test it when possible. (I leave it to be a TODO for the article readers on Medium, rsrsrs)

**Comment by pedromassango** [comment]
Thanks

**Comment by pedromassango** [comment]
Ok, tested, and added. Thanks to contribute.
